### ISSUE TITLE
Multiple nodes have root node formatting

### ISSUE THREAD

**Issue by SpiritSeal** [SpiritSeal/mindmap#20]
### Expected:
Only root node (of id 0) should have the formatting of the root node (i.e. color, undraggable, hover icon, etc).

### Actual:
Multiple nodes have the formatting of the central "root node".

### Photo:
![image](https://user-images.githubusercontent.com/45369057/190242192-75609501-10d8-4e55-bb49-7ff86164016d.png)

May be related to #10

**Comment by epodol** [comment]
There is a reference to root being `!node.parent` and `node.id === 0`.

We should always use `root = node.id === 0`.
