### ISSUE TITLE
AI Gen fails in Live Preview

### ISSUE THREAD

**Issue by SpiritSeal** [SpiritSeal/mindmap#59]
![image](https://user-images.githubusercontent.com/45369057/192610166-3e2fec9d-d6c6-498e-af2f-ed934d61aee9.png)

Some CORS issues are preventing the Firebase Functions calls from working. Please look into this and see if you can find a way to fix it, when you get a chance.

**Comment by epodol** [comment]
This is just because the functions haven't been deployed yet. A preview channel only deploys a preview of the front end, but the functions and database all are based on the data from production.
