### ISSUE TITLE
Fix Exceptionally Scuffed File Structure

### ISSUE THREAD

**Issue by SpiritSeal** [SpiritSeal/mindmap#61]

**Comment by epodol** [comment]
https://mui.com/material-ui/react-dialog/

**Comment by SpiritSeal** [comment]
Might as well make this MVP at this point since I've finished all of my other pending MVP assignments.

**Comment by SpiritSeal** [comment]
This is a lot more pressing of an issue, will make a new issue to complete Preferences Menu
